In [3]:
import re
import pandas as pd

train_phi_category = ['PATIENT', 'DOCTOR', 'USERNAME',
             'PROFESSION', 'ROOM', 'DEPARTMENT', 'HOSPITAL', 'ORGANIZATION', 'STREET', 'CITY', 'STATE', 'COUNTRY', 'ZIP', 'LOCATION-OTHER',
             'AGE', 'DATE', 'TIME', 'DURATION', 'SET',
             'PHONE', 'FAX', 'EMAIL', 'URL', 'IPADDR',
             'SSN', 'MEDICALRECORD', 'HEALTHPLAN', 'ACCOUNT', 'LICENSE', 'VEHICLE', 'DEVICE', 'BIOID', 'IDNUM','PHI']

with open("llama3/generated_sentences.txt", "r", encoding="utf-8") as f:
    lines = f.readlines()
    
    context = []
    category = []
    word = []
    
    for line in lines:
        if "\t" in line:
            left, right = line.split("\t", 1    )
            if ":" in right:
                cleft, cright = right.split(":", 1)
                context.append(left.strip())
                category.append(cleft.strip())
                word.append(cright.strip())


    
    df = pd.DataFrame({'Context': context, 'Category': category, 'Word': word})
    
    df = df.drop_duplicates()
    
    df = df[df['Category'].isin(train_phi_category)]
    df.reset_index(drop=True, inplace=True)
    
df

,Context,Category,Word
0,(1 block of the right ovary; 2 & 3 - represen...,PHI,NULL
1,C.,PHI,NULL
2,Episode No: 14M657524P,IDNUM,14M657524P
3,The tumour appears to be invading the pericoli...,PHI,NULL
4,The tumour appears to be confined to the right...,PHI,NULL
...,...,...,...
103955,Lab No: 86W74384,IDNUM,86W74384
103956,D.O.B: 21/9/2007,DATE,21/9/2007=>2007-09-21
103957,Lab No: 41D84469,IDNUM,41D84469
103958,Lab No: 81F66004,IDNUM,81F66004
103959,MICROSCOPIC (Reported by Dr H Kibby):,DOCTOR,H Kibby

In [4]:
with open("llama3/modified_sentences.txt", "w", encoding="utf-8") as f:
    for index, row in df.iterrows():
        f.write(f"{row['Context']}\t{row['Category']}: {row['Word']}\n")